project:
  type: onlimit-theme

format:
  onlimit-theme-html:
    theme:
      - brand

website:
  title: "ON LiMiT"
  site-url: "https://onlimit.org/"
  repo-url: "https://github.com/on-limit-study/main-website"
  navbar:
    pinned: true
    left:
      - text: "Menu"
        menu:
          - text: "Om ON LiMiT"
            href: about.md
          - text: "For praktiserende l√¶ger"
            href: practitioners.md
          - text: "For deltagere i pilotstudiet"
            href: participants.md
          - text: "For forskere"
            href: researchers.md
            
editor:
  markdown:
    wrap: 72
    canonical: true
